spring.application.name=backend

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/peerlearning
spring.datasource.username=postgres
spring.datasource.password=0105cs243d21

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect